#!/usr/bin/env zsh

# --- Core Utilities ---
() {
  # Neovim as default editor
  (( ${+commands[nvim]} )) && {
    alias  vim='nvim'
    alias  vimdiff='nvim -d'
  }

  # XDG-aware application aliases
  [[ -v XINITRC && -f $XINITRC ]] && alias startx="startx $XINITRC"
  [[ -f ${MBSYNCRC:-$HOME/.mbsyncrc} ]] && alias mbsync="mbsync -c ${MBSYNCRC:-$HOME/.mbsyncrc}"
}

# --- Sudo Shortcuts ---
() {
  local -a sudo_commands=(mount umount sv pacman updatedb su shutdown poweroff reboot zzz)
  for cmd in $sudo_commands; do
    (( ${+commands[$cmd]} )) && alias $cmd="sudo $cmd"
  done
}

# --- File Operations ---
se() {
  local choice
  choice=$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf --height 40% --reverse)
  [[ -n $choice ]] && $EDITOR "$HOME/.local/bin/$choice"
}

# --- Random Generators ---
nickrandom() {
  local nick=$(grep -E '^[A-Z][a-z]+(d|n|r|t|s)$' /usr/share/dict/words |shuf -n 1 )
  printf "%s" "$nick" | xclip -sel clip
  echo "Nick: $nick"
}

pw() {
  local passw=$(LC_ALL=C tr -dc 'A-Za-z0-9!@#$%^&*()_+~' < /dev/urandom | head -c 30)
  printf "%s" "$passw" | xclip -sel clip
  echo "Password: $passw"
}

# --- Network ---
wg-add() {
  (( ${+commands[nmcli]} )) && nmcli connection import type wireguard file "$@"
}

# --- Navigation ---
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# --- Package Management ---
alias pacsyu='sudo pacman -Syu'
alias pacsyyu='sudo pacman -Syyu'
alias pacscc='sudo pacman -Scc'
alias unlock='sudo rm /var/lib/pacman/db.lck'
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'
alias list="pacman -Qqe"
alias listt="pacman -Qqet"
alias listaur="pacman -Qqem"

# --- Process Management ---
alias psa="ps auxf"
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

# --- Verbose Operations ---
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -Iv'
alias mkd='mkdir -pv'
alias ffmpeg='ffmpeg -hide_banner'
alias ffprobe='ffprobe -hide_banner'
alias lsb='lsblk -o NAME,FSTYPE,SIZE,FSUSED,MOUNTPOINTS,UUID'

# --- Colorized Output ---
alias ls='ls -hN --color=auto --group-directories-first'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip -color=auto'
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
alias l.='ls -d .*'
alias ccat='highlight --out-format=ansi'

# --- YouTube Download ---
alias yt='yt-dlp --embed-metadata -i'
alias yta='yt -x -f bestaudio/best'
alias ytt='yt --skip-download --write-thumbnail'
alias yta-flac='yt -x --audio-format flac'
alias yta-mp3='yt -x --audio-format mp3'
alias yta-aac='yt -x --audio-format aac'
alias yta-best='yt -x --audio-format best'
alias yta-m4a='yt -x -f "ba[ext=m4a]"'

# --- System Info ---
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort -h | tail -200 | nl"
alias riplong="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort -h | tail -3000 | nl"

# --- Git ---
alias g='git'
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME'
alias gs='git status'
alias ga='git add .'
alias gc='git commit -m'
alias gagc='git add . && git commit -m'
alias gp='git fetch -p'
alias gcom='git checkout main'
alias gcol='git checkout -'
alias gb='git checkout -b'
alias gbl='git branch -a'
alias grv='git remote -v'
alias grb='npx git-removed-branches'
alias gcl='git clone'
alias gbr='git browse'
alias pp='git pull --rebase && git push'

# --- Misc Utilities ---
alias lf='lfub'
alias tb='nc termbin.com 9999'
alias tbc='nc termbin.com 9999 | xclip -selection clipboard'
alias e='exit'
alias ka='killall'
alias v='$EDITOR'
alias z='zathura'
alias wget='wget -c'
alias cupsd='sudo cupsd -f'
alias merge='xrdb -merge ~/.config/x11/xresources'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias update-fc="sudo fc-cache -fv"
alias irssi='irssi --config=$XDG_CONFIG_HOME/irssi/config --home=$XDG_DATA_HOME/irssi'
alias findme='curl https://am.i.mullvad.net/json'
alias xclip='xclip -selection clipboard'
alias tt='tt -notheme -noskip -blockcursor -nohighlight'
alias ref='shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutenvrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc'
