#!/bin/sh

preview() {
  chafa "$1" -f sixel -s "$2x$3" --animate off
}

file="$1"
shift
: "${lf_user_preview_offset:=1}" # Initialize preview offset with default 1

thumbnail="$LF_CHAFA_TEMPDIR/thumbnail.jpg"

case "$(file --brief --dereference --mime-type -- "$file")" in
*/*rar)
  unrar l "$file" | tail -n "+$lf_user_preview_offset"
  ;;
*/zip | */jar | */war | */ear | */oxt | */gz | */tar | */tgz | */tar.gz | */tar.bz2 | */tbz2 | */tar.txz | */txz | */7z | */lha | */alzip | */ace | */ar* | */rpm | */deb | */cab | */gz* | */bzip* | */compress | */lz* | */xz | */rzip | */lrzip | */7zip | */cpio | */vnd.android.package-archive)
  atool --list -- "$file" | tail -n "+$lf_user_preview_offset"
  ;;
*/pdf)
  pdftoppm -jpeg -jpegopt quality=50,optimize=y -f "$lf_user_preview_offset" -singlefile "$file" "$thumbnail"
  preview "$thumbnail.jpg" "$@"
  ;;
*/epub+zip | */mobi*)
  gnome-epub-thumbnailer -s 1024 "$file" "$thumbnail"
  preview "$thumbnail" "$@"
  ;;
*/msword*)
  catdoc "$file" | tail -n "+$lf_user_preview_offset"
  ;;
*officedocument*)
  docx2txt "$file" | tail -n "+$lf_user_preview_offset"
  ;;
*opendocument*)
  odt2txt "$file" | tail -n "+$lf_user_preview_offset"
  ;;
image/svg+xml)
  gm convert "$file" "$thumbnail"
  preview "$thumbnail" "$@"
  ;;
image/x-xcf)
  magick "$file" "$thumbnail"
  preview "$thumbnail" "$@"
  ;;
image/*)
  preview "$file" "$@"
  ;;
audio/*)
  mediainfo "$file" | tail -n "+$lf_user_preview_offset"
  ;;
video/*)
  ffmpegthumbnailer -s 0 -q 5 -i "$file" -o "$thumbnail" -t "$lf_user_preview_offset"
  preview "$thumbnail" "$@"
  ;;
*/pgp-encrypted)
  gpg -d -- "$file" | tail -n "+$lf_user_preview_offset"
  ;;
text/html)
  lynx -display_charset=utf-8 -dump "$file" | tail -n "+$lf_user_preview_offset"
  ;;
text/troff)
  man ./ "$file" | col -b | tail -n "+$lf_user_preview_offset"
  ;;
text/* | */xml | */json | */x-ndjson | */x-subrip | */javascript | */mbox)
  bat -p --theme ansi --terminal-width "$(($4-2))" -f "$file" | tail -n "+$lf_user_preview_offset"
  ;;
*iso*)
  iso-info --no-header -l "$file" | tail -n "+$lf_user_preview_offset"
  ;;
*/torrent)
  transmission-show "$file" | tail -n "+$lf_user_preview_offset"
  ;;
application/octet-stream)
  case "${file##*.}" in
  gpg)
    gpg -d -- "$file"
    ;;
  esac
  ;;
*)
  file -ibL "$file"
  ;;
esac

exit 127
