#!/bin/sh

setbg & # set the background with the `setbg` script
xrdb -merge ~/.config/x11/xresources &

autostart="mpd xcompmgr dunst unclutter pipewire remaps batterynotify"

for program in $autostart; do
    pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

dbus-launch --sh-syntax --exit-with-session dwm
