local options = {
  formatters_by_ft = {
    lua = { "stylua" },
    svelte = { "prettierd", "prettier", stop_after_first = true },
    astro = { "prettierd", "prettier", stop_after_first = true },
    javascript = { "prettierd", "prettier", stop_after_first = true },
    typescript = { "prettierd", "prettier", stop_after_first = true },
    javascriptreact = { "prettierd", "prettier", stop_after_first = true },
    typescriptreact = { "prettierd", "prettier", stop_after_first = true },
    json = { "prettierd", "prettier", stop_after_first = true },
    graphql = { "prettierd", "prettier", stop_after_first = true },
    java = { "google-java-format", "clang-format", stop_after_first = true },
    kotlin = { "ktlint" },
    ruby = { "standardrb" },
    markdown = { "prettierd", "prettier", stop_after_first = true },
    erb = { "htmlbeautifier" },
    html = { "htmlbeautifier" },
    bash = { "shfmt", "beautysh", stop_after_first = true },
    proto = { "buf" },
    rust = { "rustfmt" },
    yaml = { "yamlfmt" },
    toml = { "taplo" },
    css = { "prettierd", "prettier", stop_after_first = true },
    scss = { "prettierd", "prettier", stop_after_first = true },
    sh = { "shfmt", "beautysh", stop_after_first = true },
    zsh = { "beautysh" },
    go = { "gofmt" },
    xml = { "xmllint" },
    tex = { "tex-fmt", "latexindent", stop_after_first = true },
    c = { "clang-format" },
    cpp = { "clang-format" },
  },
}
return options
