#!/bin/sh

# Define configuration paths
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/wal"
dunstconf="${XDG_CONFIG_HOME:-$HOME/.config}/dunst/dunstrc"
zathuraconf="${XDG_CONFIG_HOME:-$HOME/.config}/zathura/zathurarc"

# Load colors
. "${cache_dir}/colors.sh"
(cat "${cache_dir}/sequences" >/dev/null 2>&1 &)

# Create parent directories if they don't exist
mkdir -p "${dunstconf%/*}" "${zathuraconf%/*}" >/dev/null 2>&1

# Process configuration files
for conf in "$dunstconf" "$zathuraconf"; do
    [ -f "$conf" ] && mv -f "$conf" "$conf.bak"
    ln -sf "${cache_dir}/${conf##*/}" "$conf"
done

# Restart dunst
pkill dunst; setsid -f dunst
